const A='2026-10-09',B='2026-10-10';
module.exports=[
{date:A,slug:'faq-accordion-widget',eyebrow:'FREE WIDGET',h1:'FAQ Accordion:<br><em>4 places to use it.</em>',sub:'Answer the question before it becomes an email.',kind:'steps',items:['Pricing page: clear up doubts next to the price','Service pages: explain how you work','Product pages: sizing, delivery and returns','Support page: the ten questions you always get'],foot:'One of 20 free widgets'},
{date:A,slug:'elementor-keyboard-shortcuts',eyebrow:'ELEMENTOR TIP',h1:'6 shortcuts that<br><em>save you hours.</em>',kind:'keys',items:[['Ctrl + E','Open the Finder'],['Ctrl + I','Open the Navigator'],['Ctrl + Shift + V','Paste style'],['Ctrl + D','Duplicate'],['Ctrl + Shift + M','Switch device view'],['Ctrl + P','Hide or show the panel']],foot:'Ctrl + ? lists them all'},
{date:A,slug:'mobile-sideways-scroll-fix',eyebrow:'QUICK FIX',h1:'Page scrolls sideways<br><em>on phones?</em>',kind:'steps',items:['Hide sections one by one to find the cause','Swap fixed px widths for % on mobile','Reset negative margins on the mobile view','Check slide-in animations that start off screen'],foot:'Save this for your next build'},
{date:A,slug:'pricing-table-pro',eyebrow:'PRO WIDGET',h1:'Pricing Table Pro:<br><em>built to convert.</em>',kind:'list',items:['Monthly and yearly switch with a savings badge','Animated price change','Sale prices and notes per period','Ribbons and a featured plan','Feature list with tooltips'],foot:'Pro from $14 a year. Code LAUNCH30'},
{date:A,slug:'slowest-part-of-a-build-question',eyebrow:'QUESTION FOR BUILDERS',h1:'What takes longest on<br><em>a new Elementor build?</em>',kind:'poll',items:['Mobile layout','Header and menu','Forms and email','Speed tuning'],foot:'Comment A, B, C or D',hs:68},
{date:A,slug:'geo-wordpress-blog',eyebrow:'NEW ON THE BLOG',h1:'Get cited by<br><em>AI search in 2026.</em>',sub:'Generative Engine Optimization for WordPress, in 8 steps.',kind:'list',items:['Put the answer first','One question per section','Back claims with facts and sources','Keep structured data accurate'],foot:'Read it at brightaddons.com/blog'},
{date:B,slug:'counter-widget',eyebrow:'FREE WIDGET',h1:'Counter widget:<br><em>let numbers sell.</em>',sub:'Four places where a number does the talking.',kind:'steps',items:['Home page: clients served and years in business','About page: team size and projects delivered','Case studies: the results you achieved','Landing pages: customers, reviews, downloads'],foot:'One of 20 free widgets'},
{date:B,slug:'save-as-template-tip',eyebrow:'ELEMENTOR TIP',h1:'Build it once.<br><em>Reuse it everywhere.</em>',kind:'steps',items:['Right-click a container and choose Save as Template','Give it a clear name, like "CTA band, dark"','Open the folder icon and pick My Templates to insert it','Export it as a JSON file to use on another site'],foot:'Save this for your next build'},
{date:B,slug:'blurry-images-fix',eyebrow:'QUICK FIX',h1:'Images look blurry<br><em>in Elementor?</em>',kind:'steps',items:['Set Image Resolution to Large or Full, not Thumbnail','Upload at twice the size it is shown, for sharp screens','Do not stretch an image wider than its real size','Check your image optimizer is not over-compressing'],foot:'Save this for your next build'},
{date:B,slug:'ajax-live-search',eyebrow:'PRO WIDGET',h1:'Search that answers<br><em>while they type.</em>',sub:'AJAX Live Search, in Bright Addons Pro.',kind:'list',items:['Results with images and type labels','WooCommerce prices in the results','Matching text highlighted','Keyboard navigation and a full screen mode','Still works as a normal search without JavaScript'],foot:'Pro from $14 a year. Code LAUNCH30'},
{date:B,slug:'myth-need-elementor-pro',eyebrow:'MYTH VS FACT',h1:'Do addons need<br><em>Elementor Pro?</em>',kind:'myth',items:['You must buy Elementor Pro before an addon plugin is any use.','Bright Addons works with the free version of Elementor. Free and Pro.'],foot:'20 free widgets to start with'},
{date:B,slug:'yearly-or-lifetime-question',eyebrow:'QUESTION FOR BUILDERS',h1:'How do you buy<br><em>your plugins?</em>',kind:'poll',items:['Yearly, I like steady updates','Lifetime, pay once and forget','Depends on the client','Free versions only'],foot:'Comment A, B, C or D'}];
